### ISSUE TITLE
Revisit condition for autoconfiguration

### ISSUE THREAD

**Issue by wjans** [IxorTalk/ixortalk-aws-s3-library#7]
Currently the autoconfiguration works with `@ConditionalOnProperty("com.ixortalk.s3.default-bucket")`, this is counterintuitive in scenario's where one does not want to work with a default bucket.

Default bucket functionality should be optional and autoconfiguration should not use that specific property for conditionals.

**Comment by wjans** [comment]
As a workaround the easiest thing to do is:

```
com:
    ixortalk:
        s3:
            default-bucket: ${some.meaningful.bucket.config}
```
